version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apigamestore
    restart: always
    ports:
      - "3001:3001"
      - "5556:5556"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:8.0.31
    build: .docker/mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=dbo
    ports:
      - "3307:3307"